version: 0.0
os: linux

hooks:
  ApplicationStop:
    - location: rmcontainer.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: newcontainer.sh
      timeout: 300
      runas: root
