version: 0.0
os: linux

hooks:
  ApplicationStop:
    - location: scripts/rmcontainer.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/newcontainer.sh
      timeout: 300
      runas: root
